# Generated by Django 6.1.1 on 2026-09-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sede',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
