# Generated by Django 6.1.1 on 2026-09-22 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('porcentaje_asistencia', models.FloatField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='estudiantes.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='principal.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nota_parcial', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='inscripciones.inscripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('fecha_pago', models.DateTimeField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inscripciones.inscripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'curso', 'periodo'), name='inscripcion_unica'),
        ),
    ]
